<template>
  <div id="app">
    <NavComponent />
    <div class="leftalign">
      <div class="synth-menu">
        <h4>Synth type</h4>
        <v-select :clearable="false" :disabled="disabled" :options="synthTones" v-model="synthTone" name="Instrument" class="instrument"/>
      </div>
    </div>
    <Piano :chord=chord />
    <div class="flexbox">
      <PlayButton @change="onPlayButtonClick" :disabled="disabled" :chord-loop="chordLoop" :selected-chords="selectChords" :chord="chord" :beat="beat"/>
      <ButtonPickChords @pickChordsClicked="onPickChordsChildClick" />
      <JazzifyButton :chord="chord" @jazzifyClicked="onJazzifyChildClick" />
    </div>
    <div class="keymenu">
    <MenuList :disabled="disabled" :chord-loop="chordLoop" :keys="keys" :modes="modes" :scale="scale"/>
    </div>
    <div class="dropdowns">
      <Dropdown :beat="beat" :disabled="disabled" :chord-loop="chordLoop" :positions="positions" :chords="chords" :modes="modes" :scale="scale"/>
    </div>
  </div>
</template>

<script>
//vue stuff
import vSelect from 'vue-select'
//components
import PlayButton from './components/PlayButton.vue'
import NavComponent from './components/NavComponent.vue'
import Piano from './components/Piano.vue'
import Dropdown from './components/Dropdown.vue'
import JazzifyButton from './components/JazzifyButton'
import MenuList from './components/MenuList.vue'
import ButtonPickChords from './components/ButtonPickChords'
//helpers
import { synth, fmSynth, amSynth } from './helpers/synth'
import { selectChords } from './helpers/chords'
import { getChords } from './helpers/tonal'
import { convertNoteToKeyboard } from './helpers/convertNoteToKeyboard'
//libraries
import * as Tone from 'tone'
import s11 from 'sharp11';

export default {
  name: 'App',
  components: {
    // HelloWorld,
    ButtonPickChords,
    PlayButton,
    NavComponent,
    Piano,
    Dropdown,
    JazzifyButton,
    vSelect,
    MenuList
  },
  data() {
    return {
      positions: [
        { beat: 1, chord: 'Chord 1', mode: 'Major' },
        { beat: 2, chord: 'Chord 2', mode: 'Major' },
        { beat: 3, chord: 'Chord 3', mode: 'Major' },
        { beat: 4, chord: 'Chord 4', mode: 'Major' },
      ],
      chords: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'],
      keys: ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B'],
      modes: ['Major', 'Minor'],
      scale: {key: 'C', mode: 'Major'},
      beat: this.currentBeat,
      chord: this.currentChord,
      synthTones: ['basic synth', 'metallic', 'dark'],
      synthTone: 'basic synth',
      disabled: false,
      // the tonal property is just placeholder to test the functionality, not something that will live in state.
      tonal: getChords()
    }
  },
  computed: {

    selectChords() {
      const chordArray = selectChords(this.positions, this.scale.key, this.scale.mode).map(chord => s11.chord.create(chord, 3));
      // console.log(chordArray);
      return chordArray.map(chordInfo => chordInfo.chord.map(note => {
        return `${note.name}${note.octave}`

      }));
    },
    chordLoop() {
      let synthTone = ''

      if (this.synthTone === 'basic synth') {
        synthTone = synth;
      } else if (this.synthTone === 'metallic') {
        synthTone = fmSynth;
      } else if (this.synthTone === 'dark') {
        synthTone = amSynth;
      }

      const loop = new Tone.Part((time, value) => {

      //value.note is the array of notes in the chord, s11.identify analyzes what chord it is and returns the chord name as a string
      //conditionally renders chord name as state
      this.chord = value.note;
      this.beat = Number(value.time[0]) + 1;

      synthTone.triggerAttackRelease(value.note, value.duration, time);
    }, [
      // Calls convertNotes function - which changes F## to G for example - on each chord in the array generated by selectChords
      {'time': '0:0', 'note': this.convertNotes(this.selectChords[0]), 'duration': '1m'},
      {'time': '1:0', 'note': this.convertNotes(this.selectChords[1]), 'duration': '1m'},
      {'time': '2:0', 'note': this.convertNotes(this.selectChords[2]), 'duration': '1m'},
      {'time': '3:0', 'note': this.convertNotes(this.selectChords[3]), 'duration': '1m'},
    ]).start(0)
    console.log("CUCUMBER****************",loop);
    return loop;
    },
    disablePlay() {
      let result = true;
      for (const position of this.positions) {
        if (!this.chords.find(position.chord)) {
          result = false;
        }
      }
      // console.log("POTATO*********",result);
      return result;
    }
  },

  methods: {
    randomChord() {
      const min = Math.ceil(0);
      const max = Math.floor(this.chords.length);
      const randomNumber = Math.floor(Math.random() * (max - min) + min);
      
      return this.chords[randomNumber];
      // return this.chords.length;
      // return "chordchanged";
    },

    onPickChordsChildClick() {
      // console.log("fully picked chords")
      this.chordLoop.dispose()
      for (let position of this.positions) {
        // console.log(position.chord);
        position.chord=this.randomChord()
      }
    },

    jazzifyChord(position) {
      let newPosition = position;
      //this code correctly sets to major/minor
      //but it doesn't play well with the library that interprets the data
      //it just interprets lowercase values as C major by default
      const modeNum = Math.random();
      if (modeNum < .16) {
        newPosition.mode = "dim";
      } else if (modeNum >= .16 && modeNum <= .25) {
        newPosition.mode = "aug";
      } else if (modeNum > .25 && modeNum <= .62) {
        newPosition.mode = "Major";
      } else {
        newPosition.mode = "Minor";
      }

      if (newPosition.mode == "Major" || newPosition.mode == "Minor") {
        const majorNum = Math.random();
        if (majorNum < .8) {
          newPosition.mode += "7";
        } else {
          newPosition.mode += "9";
        }
      } else {
        const seventhNum = Math.random();
        if (seventhNum < .3) {
          newPosition.mode += "7";
        } else if (seventhNum > .9) {
          newPosition.mode += "9";
        }
      }


      // console.log("POTATO*************", newPosition.chord, newPosition.mode);
      // if (Math.random() < .25) {
      //   chord += "dim";
      // }

      // if (Math.random() < .25) {
      //   chord += "9";
      // }

      return newPosition;
    },

    onJazzifyChildClick() {
      // console.log("fully jazzified")
      this.chordLoop.dispose()
      for (let position of this.positions) {
        // console.log(position.chord);
        // position.chord="II"
        position = this.jazzifyChord(position);
      }
    },
    onPlayButtonClick() {
      if (!this.disabled) {
        return this.disabled = true;
      }
      return this.disabled = false;
    },
    convertNotes(chordArray) {
      let convertedChord = chordArray.map(note => {return convertNoteToKeyboard(note)})
      return convertedChord;
    }
  }
}
</script>

<style lang="scss" scoped>  

  /* button styles are in globals.scss */


  #app {
    @import url('https://fonts.googleapis.com/css2?family=Julee&family=PT+Sans&display=swap');
    /*font-family: 'Julee', cursive;*/
    font-family: 'PT Sans', sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    margin: auto;
    margin-top: 5.5em;

    background-color: $light-pink;
    max-width: 530px;
  }

  .flexbox {
    display: flex;
    flex-wrap: nowrap;
    justify-content: space-around;
    margin: 2em;
  }

  .dropdowns {
    font-size: .75em;
    display: flex;
    align-self: flex-end;
    justify-content: center;
    
    padding-bottom: 3em;
  

  }

  .instrument {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .synth-menu {
    // margin-right: 21em;
    // margin-bottom: 1em;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .leftalign {
    margin: 2em;
    display: flex;
    justify-content: flex-start;
  }
</style>
